services:
  - type: web
    name: pyra-app
    runtime: python
    buildCommand: pip install -e .
    startCommand: python -m uvicorn main:app._starlette --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYRA_SECRET_KEY
        generateValue: true
      - key: PYRA_HOST
        value: 0.0.0.0
      - key: PYRA_DEBUG
        value: false
    healthCheckPath: /
